while(<DATA>){
   s/\[LF\]/\n/g;
   s/\[QUOT\]/\"/g;
   s/\[GT\]/\>/g;
   s/\[APOS\]/\'/g;
   s/\[AMP\]/\&/g;
 
   print "  $_";
}
  
__DATA__
#!/bin/bash[LF]#ISMAC=TRUE[LF]#set -x[LF]declare -i detected=0[LF]target=604800[LF]IOREG=[QUOT]/usr/sbin/ioreg[QUOT][LF]GREP=[QUOT]/usr/bin/grep[QUOT][LF]ID=[QUOT]`${IOREG} -rd1 -c IOPlatformExpertDevice|${GREP} -E [APOS](UUID)[APOS]|cut -d\\[QUOT] -f4`[QUOT][LF]EtherID=[QUOT]$(ifconfig en0 |awk [APOS]/ether/{gsub(/:/,[QUOT][QUOT],$2);print $2}[APOS])[QUOT][LF]Reason=[QUOT]SoftwareUpdate check is not scheduled or Downloading updates is not set for:[QUOT][LF]Expected=[QUOT]SoftwareUpdate check  should be scheduled for $target or Downloading updates should be set.[QUOT][LF]Found=[QUOT]SoftwareUpdate check is not scheduled for $target or Downloading updates not set.[QUOT][LF][LF][LF]usernames=[QUOT]$(/usr/bin/dscl localhost list /Local/Default/Users UniqueID | awk [APOS]($2[GT]=500){print $1;}[APOS])[QUOT][LF]for user in ${usernames};do[LF][LF]downplist=[QUOT]/Users/${user}/Library/Preferences/ByHost/com.apple.SoftwareUpdate.$ID[QUOT][LF]plistfile=[QUOT]/Users/${user}/Library/Preferences/ByHost/com.apple.scheduler.$ID[QUOT][LF]etherdown=[QUOT]/Users/${user}/Library/Preferences/ByHost/com.apple.SoftwareUpdate.$EtherID[QUOT][LF]etherplist=[QUOT]/Users/${user}/Library/Preferences/ByHost/com.apple.scheduler.$EtherID[QUOT][LF]   if [ -e  [QUOT]$plistfile.plist[QUOT] ];  then[LF]     [LF]       isschedled=`/usr/bin/defaults read  $plistfile  2[GT]/dev/null |grep repeatInterval|tr -cd [0-9]` [LF]       ischanged=`/usr/bin/defaults read  $plistfile  2[GT]/dev/null |grep -E [APOS]\bdate[APOS]|grep \[QUOT]201` [LF]   if [ [QUOT]$isschedled[QUOT] != [QUOT]$target[QUOT] -o -z [QUOT]$ischanged[QUOT] ];  then [LF]        detected=1 [LF]        Reason=[QUOT]${Reason} $user[QUOT][LF]   else[LF]       isautodownload=`/usr/bin/defaults read  $downplist  AutomaticDownload 2[GT]/dev/null` [LF]       if [ [QUOT]$isautodownload[QUOT] == [QUOT]0[QUOT] ]; then [LF]        detected=1 [LF]        Reason=[QUOT]${Reason} $user[QUOT][LF]       [LF]       fi[LF]       fi[LF]   elif [ -e [QUOT]${etherplist}.plist[QUOT] ]; then[LF]       [LF]       isschedled=`/usr/bin/defaults read  $etherplist  2[GT]/dev/null |grep repeatInterval|tr -cd [0-9]` [LF]       ischanged=`/usr/bin/defaults read  $etherplist  2[GT]/dev/null |grep -E [APOS]\bdate[APOS]|grep \[QUOT]201` [LF]       if [ [QUOT]$isschedled[QUOT] != [QUOT]$target[QUOT] -o -z [QUOT]$ischanged[QUOT] ];  then [LF]        detected=1 [LF]        Reason=[QUOT]${Reason} $user[QUOT][LF]       else[LF]       isautodownload=`/usr/bin/defaults read  $etherdown  AutomaticDownload 2[GT]/dev/null` [LF]       if [ [QUOT]$isautodownload[QUOT] == [QUOT]0[QUOT] ]; then [LF]        detected=1 [LF]        Reason=[QUOT]${Reason} $user[QUOT][LF]       [LF]       fi[LF]       fi[LF]   fi[LF][LF][LF]   done[LF]echo [QUOT]Detected:$detected[QUOT][LF] [LF]if [ [QUOT]$detected[QUOT] == [QUOT]1[QUOT] ]; then [LF]  echo [QUOT]Reason:$Reason[QUOT][LF]  echo [QUOT]Expected:$Expected[QUOT][LF]  echo [QUOT]Found: $Found[QUOT][LF]fi[LF] [LF]exit 0[LF][LF]